name: Psalm Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  psalm-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring

      - name: Download Psalm PHAR
        run: wget https://github.com/vimeo/psalm/releases/latest/download/psalm.phar

      # Optional: Initialize a psalm.xml config
      # (If you haven't created a psalm.xml yet, this will generate one.)
      - name: Generate psalm.xml
        run: php psalm.phar --init --src=public --src=private

      - name: Run Psalm
        run: php psalm.phar --no-cache --show-info=false
