name: PHP Code Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code_scanning:
    name: Run PHP Code Scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Static Analysis Tools
      run: |
        mkdir tools
        wget https://getcomposer.org/composer.phar -O tools/composer.phar
        php tools/composer.phar require --working-dir=tools vimeo/psalm
   
    - name: Initialize Psalm Configuration
      run: php tools/vendor/bin/psalm --init private public

    - name: Run Psalm
      run: php tools/vendor/bin/psalm --root .

